### ISSUE TITLE
Feature togglz

### ISSUE THREAD

**Issue by rajadileepkolli** [rajadilipkolli/my-spring-boot-experiments#206]
https://rieckpil.de/howto-feature-toggles-for-spring-boot-applications-with-togglz/

**Comment by rajadilipkolli** [comment]
Currently this is not supported with spring boot3

**Comment by rajadilipkolli** [comment]
> Currently this is not supported with spring boot3

4.0.0 will support spring boot 3

**Comment by rajadilipkolli** [comment]
fixed in 0c5936c6416707bbde39c04f02fb726b1f3d172a, d2567e12c0b14cc10a487d17dde9ae85d933d669
